services:
  - name: backend-organizer-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://folcarril:admin123@restfuls-apis.xeftvl2.mongodb.net/?retryWrites=true&w=majority&appName=restfuls-apis

  - name: frontend-organizer-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: HOST
        value: localhost