services:
  - name: backend-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://folcarril:admin123@restfuls-apis.xeftvl2.mongodb.net/?retryWrites=true&w=majority&appName=restfuls-apis
      - key: SERVER_SOCKET_HOST
        value: 0.0.0.0/0
      - key: SERVER_SOCKET_PORT
        value: 8000
    ports:
      - 8000

  - name: frontend-service
    type: web
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: HOST
        value: localhost
    ports:
      - 5173
